.PHONY: clean All

All:
	@echo "----------Building project:[ Jipduino_Alpha_0-2 - Release ]----------"
	@cd "Jipduino_Alpha_0-2" && "$(MAKE)" -f  "Jipduino_Alpha_0-2.mk"
clean:
	@echo "----------Cleaning project:[ Jipduino_Alpha_0-2 - Release ]----------"
	@cd "Jipduino_Alpha_0-2" && "$(MAKE)" -f  "Jipduino_Alpha_0-2.mk" clean
